### ISSUE TITLE
需求排的很清楚, 还是很 nice 的

### ISSUE THREAD

**Issue by NageNalock** [IcedSoul/WithMe3.0#1]
这个项目现在有部署在公有云上么
十月之后可以帮忙一起做啊

**Comment by IcedSoul** [comment]
wow，现在部署用的学校的服务器。因为我买的公有云服务器内存都很小跑不起来。。。内存大的太贵了 =_= 买不起。  
欢迎你来一起开发啊，需求列的不少但是进度及其缓慢2333.
先加一下微信吧～
guoxiaofengdeweixin

**Comment by IcedSoul** [comment]
@NageNalock

**Comment by NageNalock** [comment]
> wow，现在部署用的学校的服务器。因为我买的公有云服务器内存都很小跑不起来。。。内存大的太贵了 =_= 买不起。
> 欢迎你来一起开发啊，需求列的不少但是进度及其缓慢2333.
> 先加一下微信吧～
> guoxiaofengdeweixin

还在实习...时间不太充裕

**Comment by IcedSoul** [comment]
> > wow，现在部署用的学校的服务器。因为我买的公有云服务器内存都很小跑不起来。。。内存大的太贵了 =_= 买不起。
> > 欢迎你来一起开发啊，需求列的不少但是进度及其缓慢2333.
> > 先加一下微信吧～
> > guoxiaofengdeweixin
> 
> 还在实习...时间不太充裕

没事的，欢迎有空之后共同开发～ 我自己都是指不定几个月想起来写一下23333
